### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by s-gregorini003** [nodidilu/nodidilu.github.io#1]
- [x]  Resize `bg.jpg`
- [x]  Add social links in popup header
- [x]  Fix social links in pre-home page
